# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ade14590c489f95b7873f1c939772cf22a93a4d4805d00c008e2a743e3faba92a81fc1fac5d97db9c43efbc080148ee33277533b5348742de4e8ce2a40d77339

test:
  secret_key_base: 9ad5be5a9a56018d928962dadc15c0dbca43f4361052cc9a83782caa6b6e96e83f31ccce0cc076946d1eb44b3a0db252dc870f8b15d248b0e7677f252d48cb46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
